create table TB_T_RES_PIBCONR
(
    PROCESS_ID VARCHAR2(20),
  CAR      VARCHAR2(26),
  RESKD    VARCHAR2(3),
  CONTNO   VARCHAR2(17),
  CONTUKUR VARCHAR2(2),
  CONTTIPE VARCHAR2(1),
   CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);

create table TB_R_RES_PIBCONR
(
  CAR      VARCHAR2(26),
  RESKD    VARCHAR2(3),
  CONTNO   VARCHAR2(17),
  CONTUKUR VARCHAR2(2),
  CONTTIPE VARCHAR2(1),
   CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);


alter table TB_T_RES_PIBCONR
  add constraint PK_TB_T_RES_PIBCONR primary key (CAR, RESKD, CONTNO);
alter table TB_R_RES_PIBCONR
  add constraint PK_TB_R_RES_PIBCONR primary key (CAR, RESKD, CONTNO);
