create table TB_T_RES_PIBDTLDOK
(
  PROCESS_ID VARCHAR2(20),
  CAR        VARCHAR2(26),
  SERIAL     NUMBER(4),
  KDFASDTL   VARCHAR2(2),
  NOURUT     NUMBER(4),
  DOKKD      VARCHAR2(3),
  DOKNO      VARCHAR2(30),
  DOKTG      DATE,
  KDGROUPDOK VARCHAR2(3),
 
  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
)

alter table TB_T_RES_PIBDTLDOK
  add constraint PK_TB_T_RES_PIBTDTLDOK primary key (CAR, DOKKD, DOKNO,  SERIAL);


create table TB_R_RES_PIBDTLDOK
(
  CAR        VARCHAR2(26),
  SERIAL     NUMBER(4),
  KDFASDTL   VARCHAR2(2),
  NOURUT     NUMBER(4),
  DOKKD      VARCHAR2(3),
  DOKNO      VARCHAR2(30),
  DOKTG      DATE,
  KDGROUPDOK VARCHAR2(3),
 
  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
)

alter table TB_R_RES_PIBDTLDOK
  add constraint PK_TB_R_RES_PIBTDTLDOK primary key (CAR, DOKKD, DOKNO,  SERIAL);
