alter table TB_T_RES_PIBDTL add FLBARANGBARU VARCHAR2(1);
alter table TB_T_RES_PIBDTL add FLLARTAS VARCHAR2(1);
alter table TB_T_RES_PIBDTL add KATLARTAS VARCHAR2(2);
alter table TB_T_RES_PIBDTL add SPEKTARIF VARCHAR2(2);
alter table TB_T_RES_PIBDTL add DNILCUK NUMBER(18,4);
alter table TB_T_RES_PIBDTL add JMPC NUMBER(18,4);
alter table TB_T_RES_PIBDTL add SALDOAWALPC NUMBER(18,4);
alter table TB_T_RES_PIBDTL add SALDOAKHIRPC NUMBER(18,4);

alter table TB_R_RES_PIBDTL add FLBARANGBARU VARCHAR2(1);
alter table TB_R_RES_PIBDTL add FLLARTAS VARCHAR2(1);
alter table TB_R_RES_PIBDTL add KATLARTAS VARCHAR2(2);
alter table TB_R_RES_PIBDTL add SPEKTARIF VARCHAR2(2);
alter table TB_R_RES_PIBDTL add DNILCUK NUMBER(18,4);
alter table TB_R_RES_PIBDTL add JMPC NUMBER(18,4);
alter table TB_R_RES_PIBDTL add SALDOAWALPC NUMBER(18,4);
alter table TB_R_RES_PIBDTL add SALDOAKHIRPC NUMBER(18,4);

