create table TB_T_RES_PIBDTLSPEKKHUSUS
(
  PROCESS_ID VARCHAR2(20),
   CAR    VARCHAR2(26),
  SERIAL NUMBER(4),
  CAS1   VARCHAR2(8),
  CAS2   VARCHAR2(3),
 
  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);

alter table TB_T_RES_PIBDTLSPEKKHUSUS
  add constraint PK_TB_T_RES_PIBDTLSPEKKHUSUS primary key (CAR, SERIAL, CAS1, CAS2);


create table TB_R_RES_PIBDTLSPEKKHUSUS
(
   CAR    VARCHAR2(26),
  SERIAL NUMBER(4),
  CAS1   VARCHAR2(8),
  CAS2   VARCHAR2(3),
 
  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);

alter table TB_R_RES_PIBDTLSPEKKHUSUS
  add constraint PK_TB_R_RES_PIBDTLSPEKKHUSUS primary key (CAR, SERIAL, CAS1, CAS2);
