--PIB Header
alter table TB_T_RES_PIBHDR add BILLNPWP VARCHAR2(15);
alter table TB_T_RES_PIBHDR add BILLNAMA VARCHAR2(50);
alter table TB_T_RES_PIBHDR add BILLALMT VARCHAR2(70);
alter table TB_T_RES_PIBHDR add PENJUALNAMA VARCHAR2(50);
alter table TB_T_RES_PIBHDR add PENJUALALMT VARCHAR2(70);
alter table TB_T_RES_PIBHDR add PENJUALNEG VARCHAR2(2);
alter table TB_T_RES_PIBHDR add PERNYATAAN VARCHAR2(1);
alter table TB_T_RES_PIBHDR add JNSTRANS VARCHAR2(3);
alter table TB_T_RES_PIBHDR add VD VARCHAR2(1);
alter table TB_T_RES_PIBHDR add VERSIMODUL NUMBER(4);
alter table TB_T_RES_PIBHDR add NILVD NUMBER(18,2);
alter table TB_T_RES_PIBHDR modify KDHRG VARCHAR2(2);
alter table TB_T_RES_PIBHDR modify BTAMBAHAN NUMBER(12,2);
alter table TB_T_RES_PIBHDR modify DISKON NUMBER(12,2);

alter table TB_R_RES_PIBHDR add BILLNPWP VARCHAR2(15);
alter table TB_R_RES_PIBHDR add BILLNAMA VARCHAR2(50);
alter table TB_R_RES_PIBHDR add BILLALMT VARCHAR2(70);
alter table TB_R_RES_PIBHDR add PENJUALNAMA VARCHAR2(50);
alter table TB_R_RES_PIBHDR add PENJUALALMT VARCHAR2(70);
alter table TB_R_RES_PIBHDR add PENJUALNEG VARCHAR2(2);
alter table TB_R_RES_PIBHDR add PERNYATAAN VARCHAR2(1);
alter table TB_R_RES_PIBHDR add JNSTRANS VARCHAR2(3);
alter table TB_R_RES_PIBHDR add VD VARCHAR2(1);
alter table TB_R_RES_PIBHDR add VERSIMODUL NUMBER(4);
alter table TB_R_RES_PIBHDR add NILVD NUMBER(18,2);
alter table TB_R_RES_PIBHDR modify KDHRG VARCHAR2(2);
alter table TB_R_RES_PIBHDR modify BTAMBAHAN NUMBER(12,2);
alter table TB_R_RES_PIBHDR modify DISKON NUMBER(12,2);

