create table TB_T_RES_PIBKENDARAAN
(
  PROCESS_ID VARCHAR2(20),
CAR          VARCHAR2(26),
  SERIAL       NUMBER(4),
NORANGKA VARCHAR2(50),
NOMESIN VARCHAR2(50),
SILINDER NUMBER(10,2),
TAHUN VARCHAR2(4),

  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);

alter table TB_T_RES_PIBKENDARAAN
  add constraint PK_TB_T_RES_PIBKENDARAAN primary key (CAR, SERIAL);

create table TB_R_RES_PIBKENDARAAN
(
CAR          VARCHAR2(26),
  SERIAL       NUMBER(4),
NORANGKA VARCHAR2(50),
NOMESIN VARCHAR2(50),
SILINDER NUMBER(10,2),
TAHUN VARCHAR2(4),

  CREATED_BY VARCHAR2(20),
  CREATED_DT DATE,
  CHANGED_BY VARCHAR2(20),
  CHANGED_DT DATE
);

alter table TB_R_RES_PIBKENDARAAN
  add constraint PK_TB_R_RES_PIBKENDARAAN primary key (CAR, SERIAL);

