alter table TB_T_RES_PIBRES add JMKEMAS NUMBER(4);
alter table TB_T_RES_PIBRES add NOKEMAS VARCHAR2(17);
alter table TB_T_RES_PIBRES add NPWPIMP VARCHAR2(16);
alter table TB_T_RES_PIBRES add NAMAIMP VARCHAR2(50);
alter table TB_T_RES_PIBRES add ALAMATIMP VARCHAR2(70);
alter table TB_T_RES_PIBRES add IDPPJK VARCHAR2(16);
alter table TB_T_RES_PIBRES add NAMAPPJK VARCHAR2(50);
alter table TB_T_RES_PIBRES add ALAMATPPJK VARCHAR2(70);
alter table TB_T_RES_PIBRES add KODEBILL VARCHAR2(100);
alter table TB_T_RES_PIBRES add TANGGALBILL VARCHAR2(14);
alter table TB_T_RES_PIBRES add TANGGALJTTEMPO VARCHAR2(14);
alter table TB_T_RES_PIBRES add TANGGALAJU VARCHAR2(14);
alter table TB_T_RES_PIBRES add TOTALBAYAR VARCHAR2(18);
alter table TB_T_RES_PIBRES add TERBILANG VARCHAR2(70);

alter table TB_T_RES_PIBRES modify DESKRIPSI VARCHAR2(4000);

ALTER TABLE TB_T_RES_PIBRES ADD (TMPDESKRIPSI  CLOB);

UPDATE TB_T_RES_PIBRES SET TMPDESKRIPSI=DESKRIPSI;
COMMIT;

ALTER TABLE TB_T_RES_PIBRES DROP COLUMN DESKRIPSI;

ALTER TABLE TB_T_RES_PIBRES RENAME COLUMN TMPDESKRIPSI TO DESKRIPSI;



alter table TB_R_RES_PIBRES add JMKEMAS NUMBER(4);
alter table TB_R_RES_PIBRES add NOKEMAS VARCHAR2(17);
alter table TB_R_RES_PIBRES add NPWPIMP VARCHAR2(16);
alter table TB_R_RES_PIBRES add NAMAIMP VARCHAR2(50);
alter table TB_R_RES_PIBRES add ALAMATIMP VARCHAR2(70);
alter table TB_R_RES_PIBRES add IDPPJK VARCHAR2(16);
alter table TB_R_RES_PIBRES add NAMAPPJK VARCHAR2(50);
alter table TB_R_RES_PIBRES add ALAMATPPJK VARCHAR2(70);
alter table TB_R_RES_PIBRES add KODEBILL VARCHAR2(100);
alter table TB_R_RES_PIBRES add TANGGALBILL VARCHAR2(14);
alter table TB_R_RES_PIBRES add TANGGALJTTEMPO VARCHAR2(14);
alter table TB_R_RES_PIBRES add TANGGALAJU VARCHAR2(14);
alter table TB_R_RES_PIBRES add TOTALBAYAR VARCHAR2(18);
alter table TB_R_RES_PIBRES add TERBILANG VARCHAR2(70);

alter table TB_R_RES_PIBRES modify DESKRIPSI VARCHAR2(4000);

ALTER TABLE TB_R_RES_PIBRES ADD (TMPDESKRIPSI  CLOB);

UPDATE TB_R_RES_PIBRES SET TMPDESKRIPSI=DESKRIPSI;
COMMIT;

ALTER TABLE TB_R_RES_PIBRES DROP COLUMN DESKRIPSI;

ALTER TABLE TB_R_RES_PIBRES RENAME COLUMN TMPDESKRIPSI TO DESKRIPSI;
